language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-20mode

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
env:
    global:
      - JRUBY_OPTS=--debug
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libunbound2 unbound

install: bundle install --without development

script: bundle exec rake spec
